name: node-docker-ci

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Initialize Emumlation
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # Setup Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build Docker image and push to DockerHub
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: kritix/praktikportalen:latest,
      # Install caprover cli
      - name: install caprover cli
        run: npm install -g caprover
      # Trigger deploy on Caprover instance
      - name: Deploy app
        env: 
          APP_NAME: 'praktikportal'
          APP_URL: 'https://praktikportal.diplomportal.dk/'
          IMAGE_NAME: 'kritix/praktikportalen:latest'
        run: 
         'caprover deploy --caproverUrl=$APP_URL --caproverPassword=${{ secrets.CAPROVER_PASSWORD }} --imageName=$IMAGE_NAME --appName=$APP_NAME'
